language: node_js
node_js:
  - "node"
script:
  - npm run lint
  - npm test
  - npm run build
deploy:
  provider: pages
  keep_history: true
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: web_deploy
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(v[0-9]+|master)$
