language: node_js
node_js:
  - "node"
script:
  - npm run lint
  - npm test
  - npm run build
deploy:
  provider: script
  script: bash scripts/gh-pages-deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(v[0-9]+(-beta)?|master)$
